### PR TITLE
update admiral link to last release

### PR DESCRIPTION
**Pull request by dgrassellyb**
Update links to point to the new admiral multi-version docs page.

### CODE REVIEW

**Comment by bms63** [comment]
> Good to go! Checked that admiral links are valid. @bms63 - please approve and merge when you can.

I'm not involved with this package :) @rossfarrugia who is maintainer of this package?

**Review by barnett11 — APPROVED** [review]
Looks good thanks - approved for merging to devel thank you

**Comment by dgrassellyb** [comment]
merge also approved by @cicdguy, since he has not the rights to do it I merge it !

**Comment by alanaharris22** [comment]
Hello @dgrassellyb and @cicdguy, 
Hope you're well! 
We noticed that after this update our page wasn't being deployed (the workflow was failing), I tried to make a few updates to the .gitignore as it looked like it was a result of not having the doc folder but unfortunatley now the check passes but the link to site doesn't work [https://pharmaverse.github.io/datacutr/]url. Any ideas what could be going wrong? Thanks in advance! 
Alana

**Pull request merged**
