### PR TITLE
Updating special_dm_cut and date_cut to account for the case that DCU…

### PR DESCRIPTION
**Pull request by alanaharris22**
…TDTM (datacut date) is null.

Thank you for your Pull Request! [admiraldev](https://pharmaverse.github.io/admiraldev/devel/index.html) have developed this task checklist from the [Development Process Guide](https://pharmaverse.github.io/admiraldev/main/articles/development_process.html) to help with the final steps of the process. Completing the below tasks helps to ensure our reviewers can maximize their time on your code as well as making sure the datacutr codebase remains robust and consistent.   

Please check off each taskbox as an acknowledgment that you completed the task or check off that it is not relevant to your Pull Request. This checklist is part of the Github Action workflows and the Pull Request will not be merged into the `devel` branch until you have checked off each task.

- [x] Place Closes #<insert_issue_number> into the beginning of your Pull Request Title (Use Edit button in top-right if you need to update)
- [x] Code is formatted according to the [tidyverse style guide](https://style.tidyverse.org/). Run `styler::style_file()` to style R and Rmd files
- [x] Updated relevant unit tests or have written new unit tests - See [Unit Test Guide](https://pharmaverse.github.io/admiraldev/main/articles/unit_test_guidance.html#writing-unit-tests-in-admiral-)
- [x] If you removed/replaced any function and/or function parameters, did you fully follow the [deprecation guidance](https://pharmaverse.github.io/admiraldev/main/articles/programming_strategy.html#deprecation-1)?
- [x] Update to all relevant roxygen headers and examples 
- [x] Run `devtools::document()` so all `.Rd` files in the `man` folder and the `NAMESPACE` file in the project root are updated appropriately
- [x] Address any updates needed for vignettes and/or templates
- [x] Update `NEWS.md` if the changes pertain to a user-facing function (i.e. it has an `@export` tag) or documentation aimed at users (rather than developers)
- [x] Build datacutr site `pkgdown::build_site()` and check that all affected examples are displayed correctly and that all new functions occur on the "[Reference](https://pharmaverse.github.io/admiral/cran-release/reference/index.html)" page. 
- [x] Address or fix all lintr warnings and errors - `lintr::lint_package()`
- [x] Run `R CMD check` locally and address all errors and warnings - `devtools::check()`
- [x] Link the issue in the Development Section on the right hand side.
- [x] Address all merge conflicts and resolve appropriately 
- [x] Pat yourself on the back for a job well done! Much love to your accomplishment!

### CODE REVIEW

**Comment by alanaharris22** [comment]
FYI @barnett11 and @reesnj, I had a look through and made a couple of minor changes to special_dm_cut() and date_cut to account for DCUTDTC being null. I've put in some temporary code to add a message to the console if any records of DCUTDTC are null, but it'd be good to see what you both think. Anyway, can discuss more when we meet tomorrow. Thanks!

**Review by barnett11 — COMMENTED** [review]
Have tested and is working well @alanaharris22 thanks!
Small feedback, the warning message seems to have an odd wrap character within it?
```[1] "At least one patient with missing datacut date (cut_var) in the DCUT\n               (dataset_cut) dataset, all records for this/these patient(s) will be kept."```

**Review by reesnj — COMMENTED** [review]
Reviewed and both functions appear to work as expected, thanks @alanaharris22. However, I just wanted to highlight that these aren't the only two functions that need updating in order for the entire workflow to work as expected with a missing data cut date. For example, the create_dcut function currently errors if we use a missing data cut date. Does it make sense to update all functions inside one update or should we update each of our functions individually? Including @barnett11 here for his thoughts too.

**Comment by alanaharris22** [comment]
Thanks @reesnj, I didn't think about create_dcut actually, although would they use this function if they were creating a DCUT dataset with a missing cut date as we're comparing to a condition in DS?

**Review by barnett11 — APPROVED** [review]

**Pull request merged**
