### PR TITLE
Closes #188 Update process_cut to use NULL as the default for empty input arguments

### LINKED ISSUE #188: Update process_cut to use NULL as the default for empty input arguments
Update process_cut to use NULL as the default for empty input arguments

### PR DESCRIPTION
**Pull request by reesnj**
Thank you for your Pull Request! [admiraldev](https://pharmaverse.github.io/admiraldev/devel/index.html) have developed this task checklist from the [Development Process Guide](https://pharmaverse.github.io/admiraldev/main/articles/development_process.html) to help with the final steps of the process. Completing the below tasks helps to ensure our reviewers can maximize their time on your code as well as making sure the datacutr codebase remains robust and consistent.   

Please check off each taskbox as an acknowledgment that you completed the task or check off that it is not relevant to your Pull Request. This checklist is part of the Github Action workflows and the Pull Request will not be merged into the `devel` branch until you have checked off each task.

- [x] Place Closes #<insert_issue_number> into the beginning of your Pull Request Title (Use Edit button in top-right if you need to update)
- [x] Code is formatted according to the [tidyverse style guide](https://style.tidyverse.org/). Run `styler::style_file()` to style R and Rmd files
- [x] Updated relevant unit tests or have written new unit tests - See [Unit Test Guide](https://pharmaverse.github.io/admiraldev/main/articles/unit_test_guidance.html#writing-unit-tests-in-admiral-)
- [x] If you removed/replaced any function and/or function parameters, did you fully follow the [deprecation guidance](https://pharmaverse.github.io/admiraldev/main/articles/programming_strategy.html#deprecation-1)?
- [x] Update to all relevant roxygen headers and examples 
- [x] Run `devtools::document()` so all `.Rd` files in the `man` folder and the `NAMESPACE` file in the project root are updated appropriately
- [x] Address any updates needed for vignettes and/or templates
- [x] Update `NEWS.md` if the changes pertain to a user-facing function (i.e. it has an `@export` tag) or documentation aimed at users (rather than developers)
- [x] Build datacutr site `pkgdown::build_site()` and check that all affected examples are displayed correctly and that all new functions occur on the "[Reference](https://pharmaverse.github.io/admiral/cran-release/reference/index.html)" page. 
- [x] Address or fix all lintr warnings and errors - `lintr::lint_package()`
- [x] Run `R CMD check` locally and address all errors and warnings - `devtools::check()`
- [x] Link the issue in the Development Section on the right hand side.
- [x] Address all merge conflicts and resolve appropriately 
- [x] Pat yourself on the back for a job well done! Much love to your accomplishment!

### CODE REVIEW

**Review by barnett11 — CHANGES_REQUESTED** [review]
Hi @reesnj - the null setting is working fine thanks. For the messaging on mis-matched domains, this doesn't work so well if there is more than one domain mis-matching. We may need an alternative approach, i see this happening a lot with SDTM where we have so many

**Comment by reesnj** [comment]
> Hi @reesnj - the null setting is working fine thanks. For the messaging on mis-matched domains, this doesn't work so well if there is more than one domain mis-matching. We may need an alternative approach, i see this happening a lot with SDTM where we have so many

Thanks @barnett11 - this issue has now been resolved.

**Review by barnett11 — COMMENTED** [review]
Hi @reesnj - looking really good - have tested various scenarios and does what we need it to. I saw an issue appear for `styler`, do we want to update for it? Is there a reason not to?

**Comment by reesnj** [comment]
Hello @barnett11 - are you happy for me to merge this into devel?

**Review by barnett11 — APPROVED** [review]
Thanks @reesnj - yes all looking good now thnak you

**Pull request merged**
